# https://docs.npmjs.com/trusted-publishers#step-2-configure-your-cicd-workflow

name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    if: github.repository == 'vahor/typed-es'
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create release (changesets/action)
      id-token: write # OpenID Connect token needed for provenance
      pull-requests: write # to create pull request (changesets/action)
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2.2.0
      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v2.1.1
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          publish: bun run ci:publish
          version: bun run ci:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
          NPM_CONFIG_PROVENANCE: true
          HUSKY: 0
